# Generated by Django 5.1.3 on 2024-12-17 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ("code",), "verbose_name_plural": "Currencies"},
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                max_length=3,
                primary_key=True,
                serialize=False,
                verbose_name="Currency Code",
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="Currency Name"
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_rates",
                        to="definitions.currency",
                        verbose_name="Source Currency",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_rates",
                        to="definitions.currency",
                        verbose_name="Target Currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "unique_together": {("source_currency", "target_currency", "date")},
            },
        ),
    ]
